server:
  port: 8082

spring:
  application:
    name: catalog-service

logging:
  level:
    com.globalbooks.catalog: DEBUG
    org.springframework.ws: DEBUG

soap:
  service:
    url: http://192.168.1.6:8082/catalog/soap